# Generated by Django 5.1.4 on 2025-03-14 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='file_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.CreateModel(
            name='ScraperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.SlugField(blank=True, max_length=25)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('download_link', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraper_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.AlterField(
            model_name='notifications',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.scraperfile'),
        ),
        migrations.DeleteModel(
            name='ScraperFiles',
        ),
    ]
