# Generated by Django 5.1.4 on 2025-03-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_key',
            field=models.SlugField(blank=True, max_length=24),
        ),
    ]
